
theme: jekyll-theme-minimal
title: Covid-19 i Danmark
description: Grafer over smitteudvikling i Danmark baseret på data fra SSI
author: Kristoffer T. Bæk
twitter:
  username: KT_baek
github:
  username: ktbaek
  repository_url: "https://github.com/ktbaek/COVID-19-Danmark"
